#!/bin/bash
# split comma-separated orbital coefficients file to max $NNUM values in a row

NNUM=5

while IFS='' read -r line || [[ -n "$line" ]]; do

  IFS=',' read -ra numbers <<< "$line"
  let NN=${#numbers[*]}/$NNUM
  let NREST=${#numbers[*]}-$NN*$NNUM
  let II=0
  for i in $(seq 1 $NN); do
    for j in $(seq 1 $NNUM); do
      echo -n ${numbers[$II]}, 
      let II=$II+1
    done
    echo
  done
  if [ $II -lt ${#numbers[*]} ]; then
    for j in $(seq 1 $NREST); do
      echo -n ${numbers[$II]}, 
      let II=$II+1
    done
    echo
  fi

done < "$1"
